Add Kafka and Redis implementation
SlavikN14/telegram-bot-finance pull request #12
Opened 2023-11-06 15:55 UTC by SlavikN14

Add Redis and Kafka implementation and related fixes.
Add @DmitryOnopriienko for review.

2023-11-07 10:19 UTC, ajax-gnatiuk-s requested changes

2023-11-07 10:19 UTC, ajax-gnatiuk-s commented on telegram-bot/src/main/resources/application-docker.yaml
> +  ttl:minutes: 5
```suggestion
  ttl:
      minutes: 5
```

2023-11-07 10:19 UTC, ajax-gnatiuk-s commented on telegram-bot/src/main/kotlin/com/ajaxproject/telegrambot/service/telegram/TelegramUpdateDispatcherService.kt
> +                    .then(Mono.just(true))
```suggestion
                    .thenReturn(true)
```

2023-11-07 10:19 UTC, ajax-gnatiuk-s commented on telegram-bot/src/main/kotlin/com/ajaxproject/telegrambot/service/CurrencyExchangeService.kt
> +    fun addAllCurrency(arrayCurrency: Array<CurrencyExchangeResponse>): Mono<Unit> {
```suggestion
    fun addAllCurrency(currencies: Array<CurrencyExchangeResponse>): Mono<Unit> {
```

2023-11-07 10:19 UTC, ajax-gnatiuk-s commented on telegram-bot/src/main/kotlin/com/ajaxproject/telegrambot/service/CurrencyExchangeService.kt
> +    fun getCurrencyByCode(code: Int): Mono<List<MongoCurrency>> {
```suggestion
    fun getCurrenciesByCode(code: Int): Flux<MongoCurrency> {
```

2023-11-07 10:19 UTC, ajax-gnatiuk-s commented on telegram-bot/src/main/kotlin/com/ajaxproject/telegrambot/repository/CacheableRepository.kt
> +interface CacheableRepository<T> {
let's discuss offline

2023-11-07 10:19 UTC, ajax-gnatiuk-s commented on telegram-bot/src/main/kotlin/com/ajaxproject/telegrambot/configuration/TelegramBotsConfiguration.kt
> +@EnableConfigurationProperties(BotProperties::class, MonobankProperties::class, RedisProperties::class)
You have `RedisConfiguration` so move redis properties enabling to the redis configuration.

2023-11-07 11:00 UTC, DmitryOnopriienko commented on .github/workflows/github-actions.yaml
>          run: docker run -d --name nats -p 4222:4222 nats:latest
**JFYI**: You can start your services with docker-compose

2023-11-07 11:00 UTC, DmitryOnopriienko commented on finance-service/src/main/kotlin/com/ajaxproject/financeservice/model/MongoFinance.kt
> +    val id: ObjectId = ObjectId(),
Why not to make id nullable? Mongo will generate ObjectId automatically, when saving with id = null

2023-11-07 11:00 UTC, DmitryOnopriienko commented on finance-service/src/main/kotlin/com/ajaxproject/financeservice/model/MongoFinance.kt
> +}
**NIT**

```suggestion
fun MongoFinance.toProtoFinance() = FinanceMessage.newBuilder().also {
        it.userId = userId
        it.financeType = financeType
        it.amount = amount
        it.description = description
    }.build()
```

2023-11-07 14:44 UTC, DmitryOnopriienko approved these changes

2023-11-08 22:04 UTC, ajax-gnatiuk-s approved these changes

2023-11-09 13:19 UTC, merged